"""Initial schema - all Phase 1 tables plus the audit-log immutability triggers.

Revision ID: 001
Revises:
Create Date: 2026-09-14 23:57:13.482273
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordination_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('exchanges', sa.JSON(), nullable=False),
    sa.Column('time_delta_seconds', sa.Integer(), nullable=True),
    sa.Column('correlated_price_move', sa.Float(), nullable=True),
    sa.Column('volume_coordination', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('investigation_status', sa.String(length=50), nullable=True),
    sa.Column('analyst_notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coordination_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coordination_events_asset'), ['asset'], unique=False)
        batch_op.create_index('ix_coordination_events_asset_detected', ['asset', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coordination_events_detected_at'), ['detected_at'], unique=False)

    op.create_table('data_retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('compression_after_days', sa.Integer(), nullable=True),
    sa.Column('last_purge_at', sa.DateTime(), nullable=True),
    sa.Column('records_purged', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_type')
    )
    op.create_table('liquidation_cascades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('initial_liquidation_usd', sa.Float(), nullable=True),
    sa.Column('cascade_liquidations', sa.Integer(), nullable=True),
    sa.Column('total_liquidated_usd', sa.Float(), nullable=True),
    sa.Column('price_impact', sa.Float(), nullable=True),
    sa.Column('trigger_source', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('external_event', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquidation_cascades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidation_cascades_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidation_cascades_timestamp'), ['timestamp'], unique=False)

    op.create_table('market_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('exchanges_involved', sa.JSON(), nullable=True),
    sa.Column('price_at_alert', sa.Float(), nullable=False),
    sa.Column('price_change_percent', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('volume_multiplier', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_alerts_asset'), ['asset'], unique=False)
        batch_op.create_index('ix_market_alerts_asset_timestamp', ['asset', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_alerts_timestamp'), ['timestamp'], unique=False)

    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('volume_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset', 'exchange', 'timeframe', 'timestamp', name='uq_market_candles_asset_exchange_timeframe_ts')
    )
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_candles_asset'), ['asset'], unique=False)
        batch_op.create_index('ix_market_candles_asset_exchange_timestamp', ['asset', 'exchange', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_candles_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_candles_timestamp'), ['timestamp'], unique=False)

    op.create_table('sanctions_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('designating_authority', sa.String(length=20), nullable=False),
    sa.Column('un_committee', sa.String(length=50), nullable=True),
    sa.Column('country_linked', sa.String(length=3), nullable=True),
    sa.Column('designation_date', sa.DateTime(), nullable=True),
    sa.Column('programs', sa.JSON(), nullable=True),
    sa.Column('addresses', sa.JSON(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sanctions_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sanctions_entities_designating_authority'), ['designating_authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entities_imo'), ['imo'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entities_name'), ['name'], unique=False)
        batch_op.create_index('ix_sanctions_entities_name_authority', ['name', 'designating_authority'], unique=False)

    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=False),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('historical_names', sa.JSON(), nullable=True),
    sa.Column('call_sign', sa.String(length=20), nullable=True),
    sa.Column('flag_state', sa.String(length=3), nullable=False),
    sa.Column('ship_type', sa.String(length=100), nullable=True),
    sa.Column('gross_tonnage', sa.Float(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('registered_operator', sa.String(length=200), nullable=True),
    sa.Column('beneficial_owner', sa.String(length=200), nullable=True),
    sa.Column('last_port_name', sa.String(length=200), nullable=True),
    sa.Column('last_port_time', sa.DateTime(), nullable=True),
    sa.Column('current_position_lat', sa.Float(), nullable=True),
    sa.Column('current_position_lon', sa.Float(), nullable=True),
    sa.Column('current_heading', sa.Float(), nullable=True),
    sa.Column('current_speed', sa.Float(), nullable=True),
    sa.Column('ais_status', sa.String(length=50), nullable=True),
    sa.Column('last_ais_update', sa.DateTime(), nullable=True),
    sa.Column('ais_source', sa.String(length=50), nullable=True),
    sa.Column('sanctioned_status', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessels_call_sign'), ['call_sign'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessels_flag_state'), ['flag_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessels_imo'), ['imo'], unique=True)
        batch_op.create_index(batch_op.f('ix_vessels_last_ais_update'), ['last_ais_update'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessels_mmsi'), ['mmsi'], unique=True)
        batch_op.create_index('ix_vessels_mmsi_sanctioned', ['mmsi', 'sanctioned_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessels_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessels_owner_name'), ['owner_name'], unique=False)
        batch_op.create_index('ix_vessels_owner_risk', ['owner_name', 'risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessels_sanctioned_status'), ['sanctioned_status'], unique=False)

    op.create_table('port_call_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('port_name', sa.String(length=200), nullable=False),
    sa.Column('port_code', sa.String(length=20), nullable=True),
    sa.Column('port_country', sa.String(length=3), nullable=True),
    sa.Column('is_sanctioned_facility', sa.Boolean(), nullable=False),
    sa.Column('facility_risk_level', sa.String(length=50), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('dwell_time_hours', sa.Float(), nullable=True),
    sa.Column('cargo_type_predicted', sa.String(length=200), nullable=True),
    sa.Column('flags_raised', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('port_call_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_call_events_is_sanctioned_facility'), ['is_sanctioned_facility'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_call_events_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_call_events_port_name'), ['port_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_call_events_vessel_id'), ['vessel_id'], unique=False)
        batch_op.create_index('ix_port_call_events_vessel_port_time', ['vessel_id', 'port_name', 'arrival_time'], unique=False)

    op.create_table('sanctions_breaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('vessel_name', sa.String(length=200), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('flag', sa.String(length=3), nullable=True),
    sa.Column('breach_type', sa.String(length=50), nullable=False),
    sa.Column('sanctioning_authority', sa.String(length=20), nullable=False),
    sa.Column('sanctioned_entity_name', sa.String(length=200), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('location_description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('investigation_status', sa.String(length=50), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('analyst_notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sanctions_breaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sanctions_breaches_investigation_status'), ['investigation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_breaches_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_breaches_sanctioning_authority'), ['sanctioning_authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_breaches_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_sanctions_breaches_status_severity', ['investigation_status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_breaches_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_sanctions_breaches_vessel_authority', ['vessel_id', 'sanctioning_authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_breaches_vessel_id'), ['vessel_id'], unique=False)

    op.create_table('shipping_lane_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('lane_name', sa.String(length=200), nullable=False),
    sa.Column('deviation_distance_nm', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('reason_suspected', sa.String(length=300), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipping_lane_violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_lane_violations_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_lane_violations_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_lane_violations_vessel_id'), ['vessel_id'], unique=False)
        batch_op.create_index('ix_shipping_lane_violations_vessel_lane', ['vessel_id', 'lane_name'], unique=False)

    op.create_table('transshipment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_a_id', sa.Integer(), nullable=False),
    sa.Column('vessel_b_id', sa.Integer(), nullable=False),
    sa.Column('vessel_a_mmsi', sa.String(length=20), nullable=True),
    sa.Column('vessel_b_mmsi', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lon', sa.Float(), nullable=False),
    sa.Column('proximity_meters', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('investigation_status', sa.String(length=50), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('analyst_notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['vessel_a_id'], ['vessels.id'], ),
    sa.ForeignKeyConstraint(['vessel_b_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transshipment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transshipment_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_transshipment_events_vessels_timestamp', ['vessel_a_id', 'vessel_b_id', 'timestamp'], unique=False)

    op.create_table('vessel_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('course', sa.Float(), nullable=True),
    sa.Column('ais_source', sa.String(length=50), nullable=True),
    sa.Column('signal_quality', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vessel_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessel_positions_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index('ix_vessel_positions_mmsi_timestamp', ['mmsi', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessel_positions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vessel_positions_vessel_id'), ['vessel_id'], unique=False)
        batch_op.create_index('ix_vessel_positions_vessel_timestamp', ['vessel_id', 'timestamp'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('breach_id', sa.Integer(), nullable=True),
    sa.Column('sanctioned_entity_name', sa.String(length=200), nullable=True),
    sa.Column('sanctioning_authorities', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('supporting_data', sa.JSON(), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.Column('classification_level', sa.String(length=50), nullable=True),
    sa.Column('source_systems', sa.JSON(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['breach_id'], ['sanctions_breaches.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_logs_timestamp_action', ['timestamp', 'action_type'], unique=False)
        batch_op.create_index('ix_audit_logs_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_logs_vessel_timestamp', ['vessel_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###

    # audit_logs is append-only: abort any UPDATE/DELETE at the database level
    # (covers bulk statements and raw SQL that bypass the ORM listeners).
    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS trg_audit_logs_no_update BEFORE UPDATE ON audit_logs "
            "BEGIN SELECT RAISE(ABORT, 'audit_logs is immutable'); END"
        )
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS trg_audit_logs_no_delete BEFORE DELETE ON audit_logs "
            "BEGIN SELECT RAISE(ABORT, 'audit_logs is immutable'); END"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_update")
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_delete")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_vessel_timestamp')
        batch_op.drop_index('ix_audit_logs_user_timestamp')
        batch_op.drop_index('ix_audit_logs_timestamp_action')
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action_type'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('vessel_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_vessel_positions_vessel_timestamp')
        batch_op.drop_index(batch_op.f('ix_vessel_positions_vessel_id'))
        batch_op.drop_index(batch_op.f('ix_vessel_positions_timestamp'))
        batch_op.drop_index('ix_vessel_positions_mmsi_timestamp')
        batch_op.drop_index(batch_op.f('ix_vessel_positions_mmsi'))

    op.drop_table('vessel_positions')
    with op.batch_alter_table('transshipment_events', schema=None) as batch_op:
        batch_op.drop_index('ix_transshipment_events_vessels_timestamp')
        batch_op.drop_index(batch_op.f('ix_transshipment_events_timestamp'))

    op.drop_table('transshipment_events')
    with op.batch_alter_table('shipping_lane_violations', schema=None) as batch_op:
        batch_op.drop_index('ix_shipping_lane_violations_vessel_lane')
        batch_op.drop_index(batch_op.f('ix_shipping_lane_violations_vessel_id'))
        batch_op.drop_index(batch_op.f('ix_shipping_lane_violations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_shipping_lane_violations_mmsi'))

    op.drop_table('shipping_lane_violations')
    with op.batch_alter_table('sanctions_breaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sanctions_breaches_vessel_id'))
        batch_op.drop_index('ix_sanctions_breaches_vessel_authority')
        batch_op.drop_index(batch_op.f('ix_sanctions_breaches_timestamp'))
        batch_op.drop_index('ix_sanctions_breaches_status_severity')
        batch_op.drop_index(batch_op.f('ix_sanctions_breaches_severity'))
        batch_op.drop_index(batch_op.f('ix_sanctions_breaches_sanctioning_authority'))
        batch_op.drop_index(batch_op.f('ix_sanctions_breaches_mmsi'))
        batch_op.drop_index(batch_op.f('ix_sanctions_breaches_investigation_status'))

    op.drop_table('sanctions_breaches')
    with op.batch_alter_table('port_call_events', schema=None) as batch_op:
        batch_op.drop_index('ix_port_call_events_vessel_port_time')
        batch_op.drop_index(batch_op.f('ix_port_call_events_vessel_id'))
        batch_op.drop_index(batch_op.f('ix_port_call_events_port_name'))
        batch_op.drop_index(batch_op.f('ix_port_call_events_mmsi'))
        batch_op.drop_index(batch_op.f('ix_port_call_events_is_sanctioned_facility'))

    op.drop_table('port_call_events')
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vessels_sanctioned_status'))
        batch_op.drop_index('ix_vessels_owner_risk')
        batch_op.drop_index(batch_op.f('ix_vessels_owner_name'))
        batch_op.drop_index(batch_op.f('ix_vessels_name'))
        batch_op.drop_index('ix_vessels_mmsi_sanctioned')
        batch_op.drop_index(batch_op.f('ix_vessels_mmsi'))
        batch_op.drop_index(batch_op.f('ix_vessels_last_ais_update'))
        batch_op.drop_index(batch_op.f('ix_vessels_imo'))
        batch_op.drop_index(batch_op.f('ix_vessels_flag_state'))
        batch_op.drop_index(batch_op.f('ix_vessels_call_sign'))

    op.drop_table('vessels')
    with op.batch_alter_table('sanctions_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_sanctions_entities_name_authority')
        batch_op.drop_index(batch_op.f('ix_sanctions_entities_name'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entities_imo'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entities_designating_authority'))

    op.drop_table('sanctions_entities')
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_candles_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_candles_exchange'))
        batch_op.drop_index('ix_market_candles_asset_exchange_timestamp')
        batch_op.drop_index(batch_op.f('ix_market_candles_asset'))

    op.drop_table('market_candles')
    with op.batch_alter_table('market_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_alerts_severity'))
        batch_op.drop_index('ix_market_alerts_asset_timestamp')
        batch_op.drop_index(batch_op.f('ix_market_alerts_asset'))

    op.drop_table('market_alerts')
    with op.batch_alter_table('liquidation_cascades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidation_cascades_timestamp'))
        batch_op.drop_index(batch_op.f('ix_liquidation_cascades_asset'))

    op.drop_table('liquidation_cascades')
    op.drop_table('data_retention_policies')
    with op.batch_alter_table('coordination_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coordination_events_detected_at'))
        batch_op.drop_index('ix_coordination_events_asset_detected')
        batch_op.drop_index(batch_op.f('ix_coordination_events_asset'))

    op.drop_table('coordination_events')
    # ### end Alembic commands ###
