"""market bot summaries

Revision ID: 002
Revises: 001
Create Date: 2026-09-15 00:14:29.345634
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordination_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=300), nullable=True))

    with op.batch_alter_table('liquidation_cascades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=300), nullable=True))

    with op.batch_alter_table('market_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_alerts', schema=None) as batch_op:
        batch_op.drop_column('summary')

    with op.batch_alter_table('liquidation_cascades', schema=None) as batch_op:
        batch_op.drop_column('summary')

    with op.batch_alter_table('coordination_events', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
