"""sanctions tracking and evasion events

Revision ID: 003
Revises: 002
Create Date: 2026-09-15 00:39:28.690693
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions_program_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority', sa.String(length=20), nullable=False),
    sa.Column('program_name', sa.String(length=100), nullable=False),
    sa.Column('entities_in_program', sa.Integer(), nullable=True),
    sa.Column('vessels_in_program', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_on_new', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority', 'program_name', name='uq_sanctions_program_tracking_authority_program')
    )
    with op.batch_alter_table('sanctions_program_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sanctions_program_tracking_last_updated'), ['last_updated'], unique=False)

    op.create_table('evasion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('investigation_status', sa.String(length=50), nullable=True),
    sa.Column('analyst_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evasion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evasion_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evasion_events_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index(batch_op.f('ix_evasion_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_evasion_events_vessel_id'), ['vessel_id'], unique=False)
        batch_op.create_index('ix_evasion_events_vessel_type_time', ['vessel_id', 'event_type', 'timestamp'], unique=False)

    op.create_table('sanctions_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('authority', sa.String(length=20), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=300), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('previous_status', sa.JSON(), nullable=True),
    sa.Column('new_status', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('alerts_generated', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctions_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sanctions_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sanctions_updates_authority'), ['authority'], unique=False)
        batch_op.create_index('ix_sanctions_updates_authority_timestamp', ['authority', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_updates_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('sanctions_breaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sanctioned_entity_id', sa.Integer(), nullable=True))
        batch_op.alter_column('sanctioned_entity_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_sanctions_breaches_sanctioned_entity_id'), ['sanctioned_entity_id'], unique=False)
        batch_op.create_foreign_key('fk_sanctions_breaches_sanctioned_entity_id_sanctions_entities', 'sanctions_entities', ['sanctioned_entity_id'], ['id'])

    with op.batch_alter_table('sanctions_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('name_normalized', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('mmsi', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('call_sign', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vessel_flag', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('vessel_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vessel_owner', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delisting_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_seen_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.create_index('ix_sanctions_entities_active_type', ['is_active', 'entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entities_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entities_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entities_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_unique_constraint('uq_sanctions_entities_authority_source', ['designating_authority', 'source_id'])

    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historical_flags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.drop_column('destination')
        batch_op.drop_column('historical_flags')

    with op.batch_alter_table('sanctions_entities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sanctions_entities_authority_source', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sanctions_entities_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entities_mmsi'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entities_is_active'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entities_entity_type'))
        batch_op.drop_index('ix_sanctions_entities_active_type')
        batch_op.alter_column('name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('first_seen_at')
        batch_op.drop_column('delisting_date')
        batch_op.drop_column('is_active')
        batch_op.drop_column('remarks')
        batch_op.drop_column('vessel_owner')
        batch_op.drop_column('vessel_type')
        batch_op.drop_column('vessel_flag')
        batch_op.drop_column('call_sign')
        batch_op.drop_column('mmsi')
        batch_op.drop_column('name_normalized')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('sanctions_breaches', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_sanctions_breaches_sanctioned_entity_id_sanctions_entities', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sanctions_breaches_sanctioned_entity_id'))
        batch_op.alter_column('sanctioned_entity_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('sanctioned_entity_id')

    with op.batch_alter_table('sanctions_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sanctions_updates_timestamp'))
        batch_op.drop_index('ix_sanctions_updates_authority_timestamp')
        batch_op.drop_index(batch_op.f('ix_sanctions_updates_authority'))

    op.drop_table('sanctions_updates')
    with op.batch_alter_table('evasion_events', schema=None) as batch_op:
        batch_op.drop_index('ix_evasion_events_vessel_type_time')
        batch_op.drop_index(batch_op.f('ix_evasion_events_vessel_id'))
        batch_op.drop_index(batch_op.f('ix_evasion_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_evasion_events_mmsi'))
        batch_op.drop_index(batch_op.f('ix_evasion_events_event_type'))

    op.drop_table('evasion_events')
    with op.batch_alter_table('sanctions_program_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sanctions_program_tracking_last_updated'))

    op.drop_table('sanctions_program_tracking')
    # ### end Alembic commands ###
