"""ecosystem tier 1 tables

Revision ID: 004
Revises: 003
Create Date: 2026-09-15 11:15:49.639394
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain', sa.String(length=30), nullable=False),
    sa.Column('tx_hash', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('from_address', sa.String(length=200), nullable=True),
    sa.Column('to_address', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('token_type', sa.String(length=30), nullable=True),
    sa.Column('involves_mixer', sa.Boolean(), nullable=False),
    sa.Column('involves_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('involves_exchange', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('suspicious_pattern', sa.String(length=100), nullable=True),
    sa.Column('source_entity', sa.String(length=300), nullable=True),
    sa.Column('destination_entity', sa.String(length=300), nullable=True),
    sa.Column('chain_length', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_transactions'))
    )
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_amount_usd'), ['amount_usd'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_blockchain'), ['blockchain'], unique=False)
        batch_op.create_index('ix_blockchain_transactions_chain_hash', ['blockchain', 'tx_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_from_address'), ['from_address'], unique=False)
        batch_op.create_index('ix_blockchain_transactions_from_to_time', ['from_address', 'to_address', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_involves_exchange'), ['involves_exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_involves_mixer'), ['involves_mixer'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_involves_sanctioned'), ['involves_sanctioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_to_address'), ['to_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_tx_hash'), ['tx_hash'], unique=False)

    op.create_table('composite_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('shared_keys', sa.JSON(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('intelligence_summary', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_composite_alerts')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_composite_alerts_fingerprint'))
    )
    with op.batch_alter_table('composite_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_composite_alerts_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_composite_alerts_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_composite_alerts_window_start'), ['window_start'], unique=False)

    op.create_table('energy_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=300), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('production_capacity_bpd', sa.Float(), nullable=True),
    sa.Column('production_capacity_mtpa', sa.Float(), nullable=True),
    sa.Column('operator_name', sa.String(length=200), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('is_sanctioned_facility', sa.Boolean(), nullable=False),
    sa.Column('sanctioning_authority', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('tanker_calls_7d', sa.Integer(), nullable=True),
    sa.Column('tanker_calls_30d', sa.Integer(), nullable=True),
    sa.Column('estimated_utilization', sa.Float(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_facilities'))
    )
    with op.batch_alter_table('energy_facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_facilities_country'), ['country'], unique=False)
        batch_op.create_index('ix_energy_facilities_country_type', ['country', 'facility_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_facilities_facility_name'), ['facility_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_facilities_facility_type'), ['facility_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_facilities_is_sanctioned_facility'), ['is_sanctioned_facility'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_facilities_owner_name'), ['owner_name'], unique=False)

    op.create_table('geopolitical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_primary', sa.String(length=3), nullable=True),
    sa.Column('country_secondary', sa.String(length=3), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('coordinates_lat', sa.Float(), nullable=True),
    sa.Column('coordinates_lon', sa.Float(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('detected_date', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('affected_sectors', sa.JSON(), nullable=True),
    sa.Column('affected_countries', sa.JSON(), nullable=True),
    sa.Column('goldstein_scale', sa.Float(), nullable=True),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.Column('correlated_with_market', sa.Boolean(), nullable=False),
    sa.Column('correlated_with_maritime', sa.Boolean(), nullable=False),
    sa.Column('correlated_with_sanctions', sa.Boolean(), nullable=False),
    sa.Column('market_impact', sa.String(length=300), nullable=True),
    sa.Column('supply_chain_impact', sa.String(length=300), nullable=True),
    sa.Column('intelligence_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geopolitical_events'))
    )
    with op.batch_alter_table('geopolitical_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geopolitical_events_correlated_with_maritime'), ['correlated_with_maritime'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_correlated_with_market'), ['correlated_with_market'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_correlated_with_sanctions'), ['correlated_with_sanctions'], unique=False)
        batch_op.create_index('ix_geopolitical_events_country_date', ['country_primary', 'event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_country_primary'), ['country_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_country_secondary'), ['country_secondary'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_detected_date'), ['detected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_geopolitical_events_severity_date', ['severity', 'event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_geopolitical_events_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_geopolitical_events_type_date', ['event_type', 'event_date'], unique=False)

    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fetch', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=200), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('latency_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_sources')),
    sa.UniqueConstraint('source_name', name=op.f('uq_news_sources_source_name'))
    )
    op.create_table('signal_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_a_type', sa.String(length=50), nullable=False),
    sa.Column('signal_a_id', sa.Integer(), nullable=False),
    sa.Column('signal_a_summary', sa.String(length=300), nullable=True),
    sa.Column('signal_a_time', sa.DateTime(), nullable=False),
    sa.Column('signal_b_type', sa.String(length=50), nullable=False),
    sa.Column('signal_b_id', sa.Integer(), nullable=False),
    sa.Column('signal_b_summary', sa.String(length=300), nullable=True),
    sa.Column('signal_b_time', sa.DateTime(), nullable=False),
    sa.Column('correlation_type', sa.String(length=50), nullable=True),
    sa.Column('time_delta_minutes', sa.Integer(), nullable=True),
    sa.Column('shared_keys', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(length=500), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_correlations'))
    )
    with op.batch_alter_table('signal_correlations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_correlations_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_correlations_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index('ix_signal_correlations_pair', ['signal_a_type', 'signal_a_id', 'signal_b_type', 'signal_b_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_signal_correlations_signal_a_type'), ['signal_a_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_correlations_signal_b_type'), ['signal_b_type'], unique=False)

    op.create_table('wallet_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('blockchain', sa.String(length=30), nullable=False),
    sa.Column('estimated_owner', sa.String(length=300), nullable=True),
    sa.Column('wallet_count', sa.Integer(), nullable=True),
    sa.Column('linked_addresses', sa.JSON(), nullable=True),
    sa.Column('total_holdings_usd', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('includes_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_clusters')),
    sa.UniqueConstraint('cluster_id', name=op.f('uq_wallet_clusters_cluster_id'))
    )
    op.create_table('blockchain_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('wallet_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('owner_name', sa.String(length=300), nullable=True),
    sa.Column('owner_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('sanctioning_authority', sa.String(length=20), nullable=True),
    sa.Column('sanctions_programs', sa.JSON(), nullable=True),
    sa.Column('sanctions_confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('balance_native', sa.Float(), nullable=True),
    sa.Column('balance_usd', sa.Float(), nullable=True),
    sa.Column('total_inflow_native', sa.Float(), nullable=True),
    sa.Column('total_outflow_native', sa.Float(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verified_owner', sa.Boolean(), nullable=False),
    sa.Column('watch', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_entity_id'], ['sanctions_entities.id'], name=op.f('fk_blockchain_wallets_owner_entity_id_sanctions_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_wallets'))
    )
    with op.batch_alter_table('blockchain_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_blockchain'), ['blockchain'], unique=False)
        batch_op.create_index('ix_blockchain_wallets_chain_address', ['blockchain', 'address'], unique=True)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_is_sanctioned'), ['is_sanctioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_last_active'), ['last_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_last_checked'), ['last_checked'], unique=False)
        batch_op.create_index('ix_blockchain_wallets_owner_chain', ['owner_name', 'blockchain'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_owner_entity_id'), ['owner_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_owner_name'), ['owner_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_wallet_type'), ['wallet_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_wallets_watch'), ['watch'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('name_normalized', sa.String(length=300), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('registration_authority', sa.String(length=100), nullable=True),
    sa.Column('registration_country', sa.String(length=3), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('company_type', sa.String(length=150), nullable=True),
    sa.Column('entity_category', sa.String(length=50), nullable=True),
    sa.Column('entity_status', sa.String(length=30), nullable=True),
    sa.Column('registration_status', sa.String(length=30), nullable=True),
    sa.Column('industry_sector', sa.String(length=100), nullable=True),
    sa.Column('registered_address', sa.String(length=500), nullable=True),
    sa.Column('business_address', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('is_shell_company', sa.Boolean(), nullable=False),
    sa.Column('shell_company_confidence', sa.Float(), nullable=True),
    sa.Column('shell_indicators', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('linked_to_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('sanctioned_entity_id', sa.Integer(), nullable=True),
    sa.Column('sanctions_match_type', sa.String(length=50), nullable=True),
    sa.Column('sanctions_confidence', sa.Float(), nullable=True),
    sa.Column('ownership_opaque', sa.Boolean(), nullable=False),
    sa.Column('parent_reporting_exception', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dissolution_date', sa.DateTime(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('last_enriched', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sanctioned_entity_id'], ['sanctions_entities.id'], name=op.f('fk_companies_sanctioned_entity_id_sanctions_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_shell_company'), ['is_shell_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_lei'), ['lei'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_linked_to_sanctioned'), ['linked_to_sanctioned'], unique=False)
        batch_op.create_index('ix_companies_name_country', ['company_name', 'registration_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_registration_country'), ['registration_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_registration_number'), ['registration_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_sanctioned_entity_id'), ['sanctioned_entity_id'], unique=False)

    op.create_table('energy_flow_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.DateTime(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('tanker_arrivals', sa.Integer(), nullable=True),
    sa.Column('tanker_departures', sa.Integer(), nullable=True),
    sa.Column('laden_departures', sa.Integer(), nullable=True),
    sa.Column('estimated_barrels', sa.Float(), nullable=True),
    sa.Column('flagged_tankers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['energy_facilities.id'], name=op.f('fk_energy_flow_snapshots_facility_id_energy_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_flow_snapshots'))
    )
    with op.batch_alter_table('energy_flow_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_flow_snapshots_day'), ['day'], unique=False)
        batch_op.create_index('ix_energy_flow_snapshots_day_facility', ['day', 'facility_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_energy_flow_snapshots_facility_id'), ['facility_id'], unique=False)

    op.create_table('event_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geopolitical_event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('alert_timestamp', sa.DateTime(), nullable=False),
    sa.Column('alert_summary', sa.String(length=300), nullable=True),
    sa.Column('time_delta_minutes', sa.Integer(), nullable=True),
    sa.Column('time_delta_direction', sa.String(length=20), nullable=True),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('correlation_type', sa.String(length=50), nullable=True),
    sa.Column('intelligence_analysis', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['geopolitical_event_id'], ['geopolitical_events.id'], name=op.f('fk_event_correlations_geopolitical_event_id_geopolitical_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_correlations'))
    )
    with op.batch_alter_table('event_correlations', schema=None) as batch_op:
        batch_op.create_index('ix_event_correlations_alert', ['alert_type', 'alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_correlations_alert_timestamp'), ['alert_timestamp'], unique=False)
        batch_op.create_index('ix_event_correlations_event_alert', ['geopolitical_event_id', 'alert_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_correlations_geopolitical_event_id'), ['geopolitical_event_id'], unique=False)

    op.create_table('company_directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=3), nullable=True),
    sa.Column('country_of_residence', sa.String(length=3), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('sanctioned_entity_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('resignation_date', sa.DateTime(), nullable=True),
    sa.Column('red_flag_director', sa.Boolean(), nullable=False),
    sa.Column('other_appointments', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_directors_company_id_companies')),
    sa.ForeignKeyConstraint(['sanctioned_entity_id'], ['sanctions_entities.id'], name=op.f('fk_company_directors_sanctioned_entity_id_sanctions_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_directors'))
    )
    with op.batch_alter_table('company_directors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_directors_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_directors_is_sanctioned'), ['is_sanctioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_directors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_directors_name_normalized'), ['name_normalized'], unique=False)

    op.create_table('oil_tanker_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('vessel_name', sa.String(length=200), nullable=True),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('flag', sa.String(length=3), nullable=True),
    sa.Column('cargo_type', sa.String(length=50), nullable=True),
    sa.Column('cargo_volume_barrels', sa.Float(), nullable=True),
    sa.Column('origin_country', sa.String(length=3), nullable=True),
    sa.Column('destination_country', sa.String(length=3), nullable=True),
    sa.Column('loading_facility_id', sa.Integer(), nullable=True),
    sa.Column('loading_location', sa.String(length=200), nullable=True),
    sa.Column('loading_date', sa.DateTime(), nullable=True),
    sa.Column('loading_port_call_id', sa.Integer(), nullable=True),
    sa.Column('discharge_facility_id', sa.Integer(), nullable=True),
    sa.Column('discharge_location', sa.String(length=200), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_port_call_id', sa.Integer(), nullable=True),
    sa.Column('draught_departure', sa.Float(), nullable=True),
    sa.Column('draught_arrival', sa.Float(), nullable=True),
    sa.Column('laden', sa.Boolean(), nullable=True),
    sa.Column('sanctioned_route', sa.Boolean(), nullable=False),
    sa.Column('dark_oil_suspect', sa.Boolean(), nullable=False),
    sa.Column('transshipment_suspect', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discharge_facility_id'], ['energy_facilities.id'], name=op.f('fk_oil_tanker_shipments_discharge_facility_id_energy_facilities')),
    sa.ForeignKeyConstraint(['discharge_port_call_id'], ['port_call_events.id'], name=op.f('fk_oil_tanker_shipments_discharge_port_call_id_port_call_events')),
    sa.ForeignKeyConstraint(['loading_facility_id'], ['energy_facilities.id'], name=op.f('fk_oil_tanker_shipments_loading_facility_id_energy_facilities')),
    sa.ForeignKeyConstraint(['loading_port_call_id'], ['port_call_events.id'], name=op.f('fk_oil_tanker_shipments_loading_port_call_id_port_call_events')),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], name=op.f('fk_oil_tanker_shipments_vessel_id_vessels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oil_tanker_shipments'))
    )
    with op.batch_alter_table('oil_tanker_shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_dark_oil_suspect'), ['dark_oil_suspect'], unique=False)
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_destination_country'), ['destination_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_loading_date'), ['loading_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_loading_facility_id'), ['loading_facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_origin_country'), ['origin_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_sanctioned_route'), ['sanctioned_route'], unique=False)
        batch_op.create_index('ix_oil_tanker_shipments_vessel_dates', ['vessel_id', 'loading_date', 'discharge_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_oil_tanker_shipments_vessel_id'), ['vessel_id'], unique=False)

    op.create_table('ownership_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_name', sa.String(length=300), nullable=True),
    sa.Column('ultimate_owner_name', sa.String(length=300), nullable=True),
    sa.Column('ultimate_owner_type', sa.String(length=50), nullable=True),
    sa.Column('ultimate_owner_lei', sa.String(length=20), nullable=True),
    sa.Column('ultimate_owner_country', sa.String(length=3), nullable=True),
    sa.Column('chain_length', sa.Integer(), nullable=True),
    sa.Column('chain_path', sa.JSON(), nullable=True),
    sa.Column('involves_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('involves_shell_companies', sa.Boolean(), nullable=False),
    sa.Column('involves_secrecy_jurisdiction', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['companies.id'], name=op.f('fk_ownership_chains_subsidiary_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ownership_chains'))
    )
    with op.batch_alter_table('ownership_chains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ownership_chains_involves_sanctioned'), ['involves_sanctioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownership_chains_subsidiary_id'), ['subsidiary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownership_chains_ultimate_owner_name'), ['ultimate_owner_name'], unique=False)

    op.create_table('shareholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('shareholder_name', sa.String(length=300), nullable=False),
    sa.Column('shareholder_type', sa.String(length=50), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('share_percentage', sa.Float(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('shareholder_company_id', sa.Integer(), nullable=True),
    sa.Column('shareholder_lei', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('sanctioned_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_beneficial_owner', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shareholders_company_id_companies')),
    sa.ForeignKeyConstraint(['sanctioned_entity_id'], ['sanctions_entities.id'], name=op.f('fk_shareholders_sanctioned_entity_id_sanctions_entities')),
    sa.ForeignKeyConstraint(['shareholder_company_id'], ['companies.id'], name=op.f('fk_shareholders_shareholder_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shareholders'))
    )
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shareholders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_is_sanctioned'), ['is_sanctioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_shareholder_company_id'), ['shareholder_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_shareholder_name'), ['shareholder_name'], unique=False)

    op.create_table('dark_oil_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanker_id', sa.Integer(), nullable=False),
    sa.Column('tanker_name', sa.String(length=200), nullable=True),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('detected_pattern', sa.String(length=100), nullable=True),
    sa.Column('suspected_origin', sa.String(length=3), nullable=True),
    sa.Column('suspected_destination', sa.String(length=3), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('voyage_start', sa.DateTime(), nullable=True),
    sa.Column('investigation_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['oil_tanker_shipments.id'], name=op.f('fk_dark_oil_indicators_shipment_id_oil_tanker_shipments')),
    sa.ForeignKeyConstraint(['tanker_id'], ['vessels.id'], name=op.f('fk_dark_oil_indicators_tanker_id_vessels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dark_oil_indicators'))
    )
    with op.batch_alter_table('dark_oil_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dark_oil_indicators_confidence_score'), ['confidence_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_dark_oil_indicators_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dark_oil_indicators_detected_pattern'), ['detected_pattern'], unique=False)
        batch_op.create_index(batch_op.f('ix_dark_oil_indicators_mmsi'), ['mmsi'], unique=False)
        batch_op.create_index('ix_dark_oil_indicators_tanker_detected', ['tanker_id', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dark_oil_indicators_tanker_id'), ['tanker_id'], unique=False)

    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draught', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.drop_column('draught')

    with op.batch_alter_table('dark_oil_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dark_oil_indicators_tanker_id'))
        batch_op.drop_index('ix_dark_oil_indicators_tanker_detected')
        batch_op.drop_index(batch_op.f('ix_dark_oil_indicators_mmsi'))
        batch_op.drop_index(batch_op.f('ix_dark_oil_indicators_detected_pattern'))
        batch_op.drop_index(batch_op.f('ix_dark_oil_indicators_detected_at'))
        batch_op.drop_index(batch_op.f('ix_dark_oil_indicators_confidence_score'))

    op.drop_table('dark_oil_indicators')
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shareholders_shareholder_name'))
        batch_op.drop_index(batch_op.f('ix_shareholders_shareholder_company_id'))
        batch_op.drop_index(batch_op.f('ix_shareholders_is_sanctioned'))
        batch_op.drop_index(batch_op.f('ix_shareholders_company_id'))

    op.drop_table('shareholders')
    with op.batch_alter_table('ownership_chains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ownership_chains_ultimate_owner_name'))
        batch_op.drop_index(batch_op.f('ix_ownership_chains_subsidiary_id'))
        batch_op.drop_index(batch_op.f('ix_ownership_chains_involves_sanctioned'))

    op.drop_table('ownership_chains')
    with op.batch_alter_table('oil_tanker_shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_vessel_id'))
        batch_op.drop_index('ix_oil_tanker_shipments_vessel_dates')
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_sanctioned_route'))
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_origin_country'))
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_mmsi'))
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_loading_facility_id'))
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_loading_date'))
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_destination_country'))
        batch_op.drop_index(batch_op.f('ix_oil_tanker_shipments_dark_oil_suspect'))

    op.drop_table('oil_tanker_shipments')
    with op.batch_alter_table('company_directors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_directors_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_company_directors_name'))
        batch_op.drop_index(batch_op.f('ix_company_directors_is_sanctioned'))
        batch_op.drop_index(batch_op.f('ix_company_directors_company_id'))

    op.drop_table('company_directors')
    with op.batch_alter_table('event_correlations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_correlations_geopolitical_event_id'))
        batch_op.drop_index('ix_event_correlations_event_alert')
        batch_op.drop_index(batch_op.f('ix_event_correlations_alert_timestamp'))
        batch_op.drop_index('ix_event_correlations_alert')

    op.drop_table('event_correlations')
    with op.batch_alter_table('energy_flow_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_flow_snapshots_facility_id'))
        batch_op.drop_index('ix_energy_flow_snapshots_day_facility')
        batch_op.drop_index(batch_op.f('ix_energy_flow_snapshots_day'))

    op.drop_table('energy_flow_snapshots')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_sanctioned_entity_id'))
        batch_op.drop_index(batch_op.f('ix_companies_risk_score'))
        batch_op.drop_index(batch_op.f('ix_companies_registration_number'))
        batch_op.drop_index(batch_op.f('ix_companies_registration_country'))
        batch_op.drop_index(batch_op.f('ix_companies_name_normalized'))
        batch_op.drop_index('ix_companies_name_country')
        batch_op.drop_index(batch_op.f('ix_companies_linked_to_sanctioned'))
        batch_op.drop_index(batch_op.f('ix_companies_lei'))
        batch_op.drop_index(batch_op.f('ix_companies_is_shell_company'))
        batch_op.drop_index(batch_op.f('ix_companies_company_name'))

    op.drop_table('companies')
    with op.batch_alter_table('blockchain_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_watch'))
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_wallet_type'))
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_risk_score'))
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_owner_name'))
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_owner_entity_id'))
        batch_op.drop_index('ix_blockchain_wallets_owner_chain')
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_last_checked'))
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_last_active'))
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_is_sanctioned'))
        batch_op.drop_index('ix_blockchain_wallets_chain_address')
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_blockchain'))
        batch_op.drop_index(batch_op.f('ix_blockchain_wallets_address'))

    op.drop_table('blockchain_wallets')
    op.drop_table('wallet_clusters')
    with op.batch_alter_table('signal_correlations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_correlations_signal_b_type'))
        batch_op.drop_index(batch_op.f('ix_signal_correlations_signal_a_type'))
        batch_op.drop_index('ix_signal_correlations_pair')
        batch_op.drop_index(batch_op.f('ix_signal_correlations_detected_at'))
        batch_op.drop_index(batch_op.f('ix_signal_correlations_confidence'))

    op.drop_table('signal_correlations')
    op.drop_table('news_sources')
    with op.batch_alter_table('geopolitical_events', schema=None) as batch_op:
        batch_op.drop_index('ix_geopolitical_events_type_date')
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_source_id'))
        batch_op.drop_index('ix_geopolitical_events_severity_date')
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_severity'))
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_detected_date'))
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_country_secondary'))
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_country_primary'))
        batch_op.drop_index('ix_geopolitical_events_country_date')
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_correlated_with_sanctions'))
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_correlated_with_market'))
        batch_op.drop_index(batch_op.f('ix_geopolitical_events_correlated_with_maritime'))

    op.drop_table('geopolitical_events')
    with op.batch_alter_table('energy_facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_facilities_owner_name'))
        batch_op.drop_index(batch_op.f('ix_energy_facilities_is_sanctioned_facility'))
        batch_op.drop_index(batch_op.f('ix_energy_facilities_facility_type'))
        batch_op.drop_index(batch_op.f('ix_energy_facilities_facility_name'))
        batch_op.drop_index('ix_energy_facilities_country_type')
        batch_op.drop_index(batch_op.f('ix_energy_facilities_country'))

    op.drop_table('energy_facilities')
    with op.batch_alter_table('composite_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_composite_alerts_window_start'))
        batch_op.drop_index(batch_op.f('ix_composite_alerts_detected_at'))
        batch_op.drop_index(batch_op.f('ix_composite_alerts_confidence'))

    op.drop_table('composite_alerts')
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_to_address'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_risk_score'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_involves_sanctioned'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_involves_mixer'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_involves_exchange'))
        batch_op.drop_index('ix_blockchain_transactions_from_to_time')
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_from_address'))
        batch_op.drop_index('ix_blockchain_transactions_chain_hash')
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_blockchain'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_amount_usd'))

    op.drop_table('blockchain_transactions')
    # ### end Alembic commands ###
