"""ecosystem tier 2 tables

Revision ID: 006
Revises: 005
Create Date: 2026-09-15 16:50:09.658675
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('outlets', sa.JSON(), nullable=True),
    sa.Column('outlet_count', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('sample_titles', sa.JSON(), nullable=True),
    sa.Column('sample_urls', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('western_coverage', sa.Integer(), nullable=True),
    sa.Column('divergence', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('assessment', sa.String(length=500), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_narratives')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_narratives_fingerprint'))
    )
    with op.batch_alter_table('narratives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narratives_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_narratives_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_narratives_score'), ['score'], unique=False)

    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('icao_hex', sa.String(length=10), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('manufacturer_serial', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('sanctioned_entity_id', sa.Integer(), nullable=True),
    sa.Column('sanctioning_authority', sa.String(length=20), nullable=True),
    sa.Column('programs', sa.JSON(), nullable=True),
    sa.Column('watch', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lon', sa.Float(), nullable=True),
    sa.Column('last_altitude_ft', sa.Float(), nullable=True),
    sa.Column('last_callsign', sa.String(length=20), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('sightings_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sanctioned_entity_id'], ['sanctions_entities.id'], name=op.f('fk_aircraft_sanctioned_entity_id_sanctions_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aircraft'))
    )
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aircraft_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_icao_hex'), ['icao_hex'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_is_sanctioned'), ['is_sanctioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_last_checked'), ['last_checked'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_operator'), ['operator'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_registration'), ['registration'], unique=True)
        batch_op.create_index(batch_op.f('ix_aircraft_sanctioned_entity_id'), ['sanctioned_entity_id'], unique=False)

    op.create_table('aircraft_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=True),
    sa.Column('icao_hex', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_ft', sa.Float(), nullable=True),
    sa.Column('ground_speed_kts', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('callsign', sa.String(length=20), nullable=True),
    sa.Column('squawk', sa.String(length=10), nullable=True),
    sa.Column('on_ground', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('nearest_country', sa.String(length=3), nullable=True),
    sa.Column('nearest_place', sa.String(length=120), nullable=True),
    sa.Column('flight_key', sa.String(length=60), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], name=op.f('fk_aircraft_sightings_aircraft_id_aircraft')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aircraft_sightings'))
    )
    with op.batch_alter_table('aircraft_sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aircraft_sightings_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index('ix_aircraft_sightings_aircraft_time', ['aircraft_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_sightings_flight_key'), ['flight_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_sightings_registration'), ['registration'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_sightings_timestamp'), ['timestamp'], unique=False)

    op.create_table('breach_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('victim_name', sa.String(length=300), nullable=False),
    sa.Column('victim_domain', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('threat_actor', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('records_affected', sa.Integer(), nullable=True),
    sa.Column('data_classes', sa.JSON(), nullable=True),
    sa.Column('matched_company_id', sa.Integer(), nullable=True),
    sa.Column('matched_entity_id', sa.Integer(), nullable=True),
    sa.Column('relevance', sa.String(length=30), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['matched_company_id'], ['companies.id'], name=op.f('fk_breach_events_matched_company_id_companies')),
    sa.ForeignKeyConstraint(['matched_entity_id'], ['sanctions_entities.id'], name=op.f('fk_breach_events_matched_entity_id_sanctions_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breach_events'))
    )
    with op.batch_alter_table('breach_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breach_events_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_matched_company_id'), ['matched_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_relevance'), ['relevance'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_source'), ['source'], unique=False)
        batch_op.create_index('ix_breach_events_source_ref', ['source', 'source_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_breach_events_threat_actor'), ['threat_actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_events_victim_name'), ['victim_name'], unique=False)

    op.create_table('infra_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=300), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('registrar', sa.String(length=200), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('nameservers', sa.JSON(), nullable=True),
    sa.Column('resolves_to', sa.JSON(), nullable=True),
    sa.Column('asn', sa.String(length=30), nullable=True),
    sa.Column('asn_org', sa.String(length=200), nullable=True),
    sa.Column('hosting_country', sa.String(length=3), nullable=True),
    sa.Column('certificate_count', sa.Integer(), nullable=True),
    sa.Column('certificate_names', sa.JSON(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_infra_assets_company_id_companies')),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctions_entities.id'], name=op.f('fk_infra_assets_entity_id_sanctions_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_infra_assets'))
    )
    with op.batch_alter_table('infra_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infra_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_infra_assets_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_infra_assets_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_infra_assets_entity_name'), ['entity_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_infra_assets_hosting_country'), ['hosting_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_infra_assets_last_checked'), ['last_checked'], unique=False)
        batch_op.create_index('ix_infra_assets_type_value', ['asset_type', 'value'], unique=True)
        batch_op.create_index(batch_op.f('ix_infra_assets_value'), ['value'], unique=False)

    op.create_table('legal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('court', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('matched_entity_id', sa.Integer(), nullable=True),
    sa.Column('matched_entity_name', sa.String(length=300), nullable=True),
    sa.Column('matched_company_id', sa.Integer(), nullable=True),
    sa.Column('query_used', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('penalty_usd', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['matched_company_id'], ['companies.id'], name=op.f('fk_legal_events_matched_company_id_companies')),
    sa.ForeignKeyConstraint(['matched_entity_id'], ['sanctions_entities.id'], name=op.f('fk_legal_events_matched_entity_id_sanctions_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_events'))
    )
    with op.batch_alter_table('legal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_events_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_events_matched_entity_id'), ['matched_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_events_matched_entity_name'), ['matched_entity_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_events_source'), ['source'], unique=False)
        batch_op.create_index('ix_legal_events_source_ref', ['source', 'source_id'], unique=True)

    with op.batch_alter_table('geopolitical_events', schema=None) as batch_op:
        batch_op.create_index('ix_geopolitical_events_source_ref', ['source', 'source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geopolitical_events', schema=None) as batch_op:
        batch_op.drop_index('ix_geopolitical_events_source_ref')

    with op.batch_alter_table('legal_events', schema=None) as batch_op:
        batch_op.drop_index('ix_legal_events_source_ref')
        batch_op.drop_index(batch_op.f('ix_legal_events_source'))
        batch_op.drop_index(batch_op.f('ix_legal_events_matched_entity_name'))
        batch_op.drop_index(batch_op.f('ix_legal_events_matched_entity_id'))
        batch_op.drop_index(batch_op.f('ix_legal_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_legal_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_legal_events_discovered_at'))

    op.drop_table('legal_events')
    with op.batch_alter_table('infra_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infra_assets_value'))
        batch_op.drop_index('ix_infra_assets_type_value')
        batch_op.drop_index(batch_op.f('ix_infra_assets_last_checked'))
        batch_op.drop_index(batch_op.f('ix_infra_assets_hosting_country'))
        batch_op.drop_index(batch_op.f('ix_infra_assets_entity_name'))
        batch_op.drop_index(batch_op.f('ix_infra_assets_entity_id'))
        batch_op.drop_index(batch_op.f('ix_infra_assets_company_id'))
        batch_op.drop_index(batch_op.f('ix_infra_assets_asset_type'))

    op.drop_table('infra_assets')
    with op.batch_alter_table('breach_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breach_events_victim_name'))
        batch_op.drop_index(batch_op.f('ix_breach_events_threat_actor'))
        batch_op.drop_index('ix_breach_events_source_ref')
        batch_op.drop_index(batch_op.f('ix_breach_events_source'))
        batch_op.drop_index(batch_op.f('ix_breach_events_sector'))
        batch_op.drop_index(batch_op.f('ix_breach_events_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_breach_events_relevance'))
        batch_op.drop_index(batch_op.f('ix_breach_events_matched_company_id'))
        batch_op.drop_index(batch_op.f('ix_breach_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_breach_events_discovered_at'))
        batch_op.drop_index(batch_op.f('ix_breach_events_country'))

    op.drop_table('breach_events')
    with op.batch_alter_table('aircraft_sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircraft_sightings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_aircraft_sightings_registration'))
        batch_op.drop_index(batch_op.f('ix_aircraft_sightings_flight_key'))
        batch_op.drop_index('ix_aircraft_sightings_aircraft_time')
        batch_op.drop_index(batch_op.f('ix_aircraft_sightings_aircraft_id'))

    op.drop_table('aircraft_sightings')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircraft_sanctioned_entity_id'))
        batch_op.drop_index(batch_op.f('ix_aircraft_registration'))
        batch_op.drop_index(batch_op.f('ix_aircraft_operator'))
        batch_op.drop_index(batch_op.f('ix_aircraft_last_seen'))
        batch_op.drop_index(batch_op.f('ix_aircraft_last_checked'))
        batch_op.drop_index(batch_op.f('ix_aircraft_is_sanctioned'))
        batch_op.drop_index(batch_op.f('ix_aircraft_icao_hex'))
        batch_op.drop_index(batch_op.f('ix_aircraft_country'))

    op.drop_table('aircraft')
    with op.batch_alter_table('narratives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narratives_score'))
        batch_op.drop_index(batch_op.f('ix_narratives_last_seen'))
        batch_op.drop_index(batch_op.f('ix_narratives_first_seen'))

    op.drop_table('narratives')
    # ### end Alembic commands ###
