"""port state control events

Revision ID: 007
Revises: 006
Create Date: 2026-09-15 18:55:23.325810
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psc_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('ship_name', sa.String(length=200), nullable=True),
    sa.Column('flag', sa.String(length=3), nullable=True),
    sa.Column('ship_type', sa.String(length=100), nullable=True),
    sa.Column('gross_tonnage', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('class_society', sa.String(length=200), nullable=True),
    sa.Column('port', sa.String(length=200), nullable=True),
    sa.Column('port_country', sa.String(length=3), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('deficiencies', sa.JSON(), nullable=True),
    sa.Column('deficiency_count', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('vessel_flagged', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], name=op.f('fk_psc_events_vessel_id_vessels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_psc_events'))
    )
    with op.batch_alter_table('psc_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psc_events_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_flag'), ['flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_imo'), ['imo'], unique=False)
        batch_op.create_index('ix_psc_events_imo_date', ['imo', 'event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_port_country'), ['port_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_ship_name'), ['ship_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_source'), ['source'], unique=False)
        batch_op.create_index('ix_psc_events_source_ref', ['source', 'source_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_psc_events_vessel_flagged'), ['vessel_flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_psc_events_vessel_id'), ['vessel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psc_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psc_events_vessel_id'))
        batch_op.drop_index(batch_op.f('ix_psc_events_vessel_flagged'))
        batch_op.drop_index('ix_psc_events_source_ref')
        batch_op.drop_index(batch_op.f('ix_psc_events_source'))
        batch_op.drop_index(batch_op.f('ix_psc_events_ship_name'))
        batch_op.drop_index(batch_op.f('ix_psc_events_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_psc_events_port_country'))
        batch_op.drop_index('ix_psc_events_imo_date')
        batch_op.drop_index(batch_op.f('ix_psc_events_imo'))
        batch_op.drop_index(batch_op.f('ix_psc_events_flag'))
        batch_op.drop_index(batch_op.f('ix_psc_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_psc_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_psc_events_discovered_at'))
        batch_op.drop_index(batch_op.f('ix_psc_events_company'))

    op.drop_table('psc_events')
    # ### end Alembic commands ###
